# Generated by Django 4.2.2 on 2023-06-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.CharField(default='dummy value', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='edu_type',
            field=models.CharField(choices=[('diploma', 'diploma'), ('certificate', 'certificate')], max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='compagny',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='job_title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='place',
            field=models.CharField(max_length=250),
        ),
    ]
