# Generated by Django 4.2.2 on 2023-06-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_education_end_date_alter_education_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deployment',
            field=models.URLField(default='https://www.github.com/gros-pataplouf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='github',
            field=models.URLField(default='https://app.vercel.com'),
            preserve_default=False,
        ),
    ]
