# Generated by Django 4.2.2 on 2023-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_project_deployment_project_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='compagny',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
