# Generated by Django 4.2.2 on 2023-06-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_alter_project_deployment_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
