# Generated by Django 4.2.2 on 2023-06-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
