# Generated by Django 4.2.2 on 2023-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_remove_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
