# Generated by Django 4.2.4 on 2023-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_alter_workexperience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Tooling', 'Tooling'), ('Databases', 'Databases'), ('Others', 'Others'), ('Languages', 'Languages'), ('Soft Skills', 'Soft Skills')], max_length=50),
        ),
    ]
