# Generated by Django 4.2.5 on 2023-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0016_remove_education_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltranslation',
            name='skill_type',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Coding', 'Coding'), ('Frontend', 'Frontend'), ('Databases', 'Databases'), ('Tooling', 'Tooling'), ('Providers', 'Providers'), ('General', 'General')], max_length=50),
        ),
    ]
