# Generated by Django 4.2.5 on 2023-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0018_alter_skilltranslation_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltranslation',
            name='skill_type',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Coding', 'Coding'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Databases', 'Databases'), ('Tooling', 'Tooling'), ('Providers', 'Providers'), ('Other', 'Other')], max_length=50),
        ),
    ]
