# Generated by Django 4.2.5 on 2023-10-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0020_remove_educationtranslation_edu_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationtranslation',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='workexperiencetranslation',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
