# Generated by Django 4.2.5 on 2023-10-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0023_alter_educationtranslation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltranslation',
            name='skill_type',
            field=models.CharField(choices=[('Languages', 'Languages'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Databases', 'Databases'), ('Tooling', 'Tooling'), ('Webdesign', 'Webdesign'), ('Other', 'Other')], max_length=50),
        ),
    ]
