# Generated by Django 4.2.5 on 2023-11-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0024_alter_skilltranslation_skill_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='educationtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='workexperiencetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='workexperiencetranslation',
            name='master',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='EducationTranslation',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
        migrations.DeleteModel(
            name='WorkExperienceTranslation',
        ),
    ]
